[build-system]
requires = [
    "setuptools>=65",
    "wheel",
    "pybind11>=2.12.0",
]

build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
build = "cp38-* cp39-* cp310-* cp311-* cp312-* cp313-*"
